version: '3'
services: 
  grafana_web: 
    image: grafana/grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-conf:/etc/grafana 
    links: 
      - prometheus
    ports: 
      - "3000:3000"
  prometheus: 
    image: prom/prometheus
    ports: 
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - prometheus-conf:/etc/prometheus  
volumes:
  grafana-data:
  prometheus-data:
  grafana-conf:
  prometheus-conf:        
