version: '3'
services: 
  grafana_web: 
    image: grafana/grafana
    volumes:
      - grafana-data:/var/lib/grafana
    links: 
      - prometheus
    ports: 
      - "3000:3000"
  prometeus: 
    image: prom/prometheus
    ports: 
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
volumes:
  grafana-data:
  prometheus-data:
